// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    id,
    title,
    url,
    description,
    feed_id,
    published_at,
    updated_at,
    created_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, title, url, description, feed_id, published_at, updated_at, created_at
`

type CreatePostParams struct {
	ID          uuid.UUID
	Title       sql.NullString
	Url         string
	Description sql.NullString
	FeedID      uuid.UUID
	PublishedAt time.Time
	UpdatedAt   time.Time
	CreatedAt   time.Time
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.FeedID,
		arg.PublishedAt,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.FeedID,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPostsByUser = `-- name: ListPostsByUser :many
SELECT 
    posts.id,
    posts.title,
    posts.url,
    posts.description,
    posts.feed_id,
    posts.published_at,
    posts.updated_at,
    posts.created_at
FROM posts
JOIN feed ON posts.feed_id = feed.id
WHERE feed.user_id = $1
ORDER BY posts.published_at DESC
LIMIT $2
`

type ListPostsByUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListPostsByUser(ctx context.Context, arg ListPostsByUserParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.FeedID,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
